# Generated by Django 4.1 on 2022-08-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lolo',
        ),
    ]
