# Generated by Django 4.1 on 2022-08-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0004_delete_lolo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
