# Generated by Django 4.1 on 2022-08-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='employee/', verbose_name='Фото')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('title', models.CharField(max_length=255, verbose_name='Должность')),
                ('quote', models.CharField(max_length=255, verbose_name='Цитата')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
            ],
        ),
    ]
