# Generated by Django 4.1 on 2022-08-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0007_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
