# Generated by Django 4.1 on 2022-08-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0008_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='service/', verbose_name='Фото')),
                ('type', models.CharField(max_length=255, verbose_name='Тип услуги')),
                ('doctor', models.CharField(default='врач-терапевт', max_length=255, verbose_name='Прием ведет')),
                ('title', models.CharField(max_length=1000, verbose_name='Описание')),
                ('main', models.CharField(max_length=100, verbose_name='Первичный прием')),
                ('second', models.CharField(max_length=100, verbose_name='Вторичный прием')),
            ],
        ),
    ]
