# Generated by Django 4.1 on 2022-08-09 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0009_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='main',
            new_name='first',
        ),
    ]
