# Generated by Django 4.1 on 2022-08-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0011_remove_services_first_remove_services_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
