# Generated by Django 4.1 on 2022-08-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0013_reviews_alter_employee_options_alter_links_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='published',
            field=models.CharField(choices=[('published', 'Опубликован'), ('unpublished', 'Не опубликован')], default='published', max_length=50),
        ),
    ]
