# Generated by Django 4.1 on 2022-08-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0014_reviews_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
    ]
