# Generated by Django 4.1 on 2022-08-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0016_blog_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
