# Generated by Django 4.1 on 2022-08-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0018_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
