# Generated by Django 4.1 on 2022-08-16 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0020_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('philosophyTitle', models.CharField(max_length=255, verbose_name='Философия Заголовок')),
                ('philosophy', models.CharField(max_length=255, verbose_name='Философия подзаголовок')),
                ('philosophyPhoto', models.ImageField(upload_to='main/', verbose_name='Философия Фото')),
                ('serviceTitle', models.CharField(max_length=255, verbose_name='Услуга Заголовок')),
                ('serviceSubtitle', models.CharField(max_length=255, verbose_name='Услуга подзаголовок')),
                ('serviceButtonSubtitle', models.CharField(max_length=255, verbose_name='Услуга нижний подзаголовок')),
                ('teamTitle', models.CharField(max_length=255, verbose_name='Команда Заголовок')),
                ('teamSubtitle', models.CharField(max_length=255, verbose_name='Команда подзаголовок')),
                ('teamPhoto', models.ImageField(upload_to='main/', verbose_name='Команда Фото')),
                ('faceToFaceTitle', models.CharField(max_length=255, verbose_name='F2F Заголовок')),
                ('faceToFaceSubtitle', models.CharField(max_length=255, verbose_name='F2F подзаголовок')),
                ('reviewTitle', models.CharField(max_length=255, verbose_name='Отзыв Заголовок')),
                ('reviewSubtitle', models.CharField(max_length=255, verbose_name='Отзыв подзаголовок')),
                ('reviewPhoto', models.ImageField(upload_to='main/', verbose_name='Отзыв Фото')),
                ('BlogTitle', models.CharField(max_length=255, verbose_name='Блог Заголовок')),
                ('BlogSubtitle', models.CharField(max_length=255, verbose_name='Блог подзаголовок')),
                ('contactsTitle', models.CharField(max_length=255, verbose_name='Контакты Заголовок')),
            ],
            options={
                'verbose_name': 'Главная',
                'verbose_name_plural': 'Главная',
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Блог', 'verbose_name_plural': 'Блог'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Терапия', 'verbose_name_plural': 'Терапии'},
        ),
        migrations.AddField(
            model_name='services',
            name='buttonname',
            field=models.CharField(default='Записаться на приём', max_length=255, verbose_name='Название кнопки'),
        ),
        migrations.AlterField(
            model_name='services',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Название терапии'),
        ),
        migrations.CreateModel(
            name='UnderServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='underServices/', verbose_name='Фото')),
                ('undertype', models.CharField(default='название терапии', max_length=255, verbose_name='Название терапии')),
                ('doctor', models.CharField(default='врач-терапевт', max_length=255, verbose_name='Прием ведет')),
                ('title', models.TextField(verbose_name='Описание')),
                ('buttonname', models.CharField(default='Записаться на приём', max_length=255, verbose_name='Название кнопки')),
                ('maintype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='astramedClinic.services', verbose_name='Главная терапия')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
            },
        ),
    ]
