# Generated by Django 4.1 on 2022-08-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0021_mainmodel_alter_blog_options_alter_services_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='категория', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория для блога',
                'verbose_name_plural': 'Категории для блогов',
            },
        ),
    ]
