# Generated by Django 4.1 on 2022-08-16 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0022_categoryblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='astramedClinic.categoryblog', verbose_name='Категория'),
        ),
    ]
