# Generated by Django 4.1 on 2022-08-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0023_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='blogs/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='employee/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='philosophyPhoto',
            field=models.ImageField(max_length=255, upload_to='main/', verbose_name='Философия Фото'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='reviewPhoto',
            field=models.ImageField(max_length=255, upload_to='main/', verbose_name='Отзыв Фото'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='teamPhoto',
            field=models.ImageField(max_length=255, upload_to='main/', verbose_name='Команда Фото'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='img/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='service/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='underservices',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='underServices/', verbose_name='Фото'),
        ),
    ]
