# Generated by Django 4.1 on 2022-08-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0026_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='therapy',
            field=models.CharField(default='Массаж', max_length=255, verbose_name='Терапия'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
    ]
