# Generated by Django 4.1 on 2022-08-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0027_applications_therapy_alter_applications_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Должность')),
                ('photo', models.ImageField(max_length=255, upload_to='jobs/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название партнера')),
                ('photo', models.ImageField(max_length=255, upload_to='partners/', verbose_name='Фото')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceFile', models.FileField(max_length=255, upload_to='priceList/', verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Прайс Лист',
                'verbose_name_plural': 'Прайс Листы',
            },
        ),
    ]
