# Generated by Django 4.1 on 2022-08-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0028_jobs_partners_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
