# Generated by Django 4.1 on 2022-08-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0029_alter_blog_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Наш адрес')),
                ('worktime', models.CharField(max_length=255, verbose_name='Время работы')),
                ('mainnumber', models.CharField(max_length=255, verbose_name='Номер телефона №2')),
                ('telegram', models.CharField(max_length=255, verbose_name='Телеграм')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AlterField(
            model_name='links',
            name='title',
            field=models.CharField(choices=[('Instagram', 'Инстаграм'), ('Telegram', 'Телеграм'), ('Facebook', 'Фейсбук')], max_length=50, verbose_name='Соц.Сеть'),
        ),
    ]
