# Generated by Django 4.1 on 2022-08-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0030_contacs_alter_links_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacs',
            name='secondnumber',
            field=models.CharField(default='', max_length=255, verbose_name='Номер телефона №2'),
        ),
        migrations.AlterField(
            model_name='contacs',
            name='mainnumber',
            field=models.CharField(max_length=255, verbose_name='Номер телефона №1'),
        ),
    ]
