# Generated by Django 4.1 on 2022-09-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0031_contacs_secondnumber_alter_contacs_mainnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacs',
            name='parking',
            field=models.TextField(default='', verbose_name='Парковка'),
        ),
        migrations.AddField(
            model_name='contacs',
            name='transport',
            field=models.TextField(default='', verbose_name='Общественный транспорт'),
        ),
        migrations.AlterField(
            model_name='contacs',
            name='telegram',
            field=models.CharField(max_length=255, verbose_name='Телеграм/SMS'),
        ),
        migrations.AlterField(
            model_name='links',
            name='title',
            field=models.CharField(choices=[('instagram', 'Инстаграм'), ('telegram', 'Телеграм'), ('facebook', 'Фейсбук')], max_length=50, verbose_name='Соц.Сеть'),
        ),
    ]
