# Generated by Django 4.1 on 2022-09-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0032_contacs_parking_contacs_transport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutPageTitle', models.CharField(max_length=255, verbose_name='Шапка')),
                ('AboutPageServicesTitle', models.CharField(max_length=255, verbose_name='Заголовок услуг')),
                ('AboutPageServicesSubtitle', models.CharField(max_length=255, verbose_name='Подзаголовок услуг')),
            ],
            options={
                'verbose_name': 'Страница о нас',
                'verbose_name_plural': 'Страница о нас',
            },
        ),
        migrations.RenameModel(
            old_name='MainModel',
            new_name='MainPage',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Страница Главная', 'verbose_name_plural': 'Страница Главная'},
        ),
        migrations.AlterModelOptions(
            name='pricelist',
            options={'verbose_name': 'Прайс Лист', 'verbose_name_plural': 'Прайс Лист'},
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
