# Generated by Django 4.1 on 2022-09-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0034_remove_partners_photo_partners_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='color',
            field=models.CharField(choices=[('partner__orange', 'Оранжевый'), ('partner__yellow', 'Жёлтый'), ('partner__grey', 'Серый')], default=('partner__grey', 'Серый'), max_length=50, verbose_name='Цвет'),
        ),
    ]
