# Generated by Django 4.1 on 2022-09-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0035_alter_partners_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CooperationTitle', models.CharField(max_length=255, verbose_name='Шапка')),
                ('CooperationPageTitle', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('CooperationPageSubtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Страница сотрудничества',
                'verbose_name_plural': 'Страница сотрудничества',
            },
        ),
    ]
