# Generated by Django 4.1 on 2022-09-05 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0036_cooperationpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2022, 9, 5), verbose_name='Время'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('process', 'В процессе'), ('done', 'Завершён')], default=('new', 'Новая'), max_length=50, verbose_name='Цвет'),
        ),
    ]
