# Generated by Django 4.1 on 2022-09-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0037_applications_date_applications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
    ]
