# Generated by Django 4.1 on 2022-09-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0039_applications_finish_date_alter_applications_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='info',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='partners',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='services',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='underservices',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
    ]
