# Generated by Django 4.1 on 2022-09-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0040_employee_published_info_published_jobs_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='after',
            field=models.ImageField(max_length=255, null=True, upload_to='service/after/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='services',
            name='before',
            field=models.ImageField(max_length=255, null=True, upload_to='service/before/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='underservices',
            name='after',
            field=models.ImageField(max_length=255, null=True, upload_to='underServices/after/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='underservices',
            name='before',
            field=models.ImageField(max_length=255, null=True, upload_to='underServices/before/', verbose_name='Фото'),
        ),
    ]
