# Generated by Django 4.1 on 2022-09-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0041_services_after_services_before_underservices_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='doctor',
            field=models.CharField(max_length=255, null=True, verbose_name='Доктор'),
        ),
    ]
