# Generated by Django 4.1 on 2022-09-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0042_reviews_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='doctor',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Доктор'),
        ),
    ]
