# Generated by Django 4.1 on 2022-09-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0044_alter_reviews_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='doctor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доктор'),
        ),
    ]
