# Generated by Django 4.1 on 2022-09-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0045_applications_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='therapy',
            field=models.CharField(blank=True, default='Массаж', max_length=255, null=True, verbose_name='Терапия'),
        ),
        migrations.AlterField(
            model_name='services',
            name='after',
            field=models.ImageField(max_length=255, null=True, upload_to='service/after/', verbose_name='Фото После'),
        ),
        migrations.AlterField(
            model_name='services',
            name='before',
            field=models.ImageField(max_length=255, null=True, upload_to='service/before/', verbose_name='Фото До '),
        ),
        migrations.AlterField(
            model_name='underservices',
            name='after',
            field=models.ImageField(max_length=255, null=True, upload_to='underServices/after/', verbose_name='Фото После'),
        ),
        migrations.AlterField(
            model_name='underservices',
            name='before',
            field=models.ImageField(max_length=255, null=True, upload_to='underServices/before/', verbose_name='Фото До'),
        ),
    ]
