# Generated by Django 4.1 on 2022-09-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0046_alter_applications_therapy_alter_services_after_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headerTitle', models.CharField(default='', max_length=255, verbose_name='Услуги Заголовок')),
                ('faceToFaceTitle', models.CharField(default='', max_length=255, verbose_name='F2F Заголовок')),
                ('faceToFaceSubtitle', models.CharField(default='', max_length=255, verbose_name='F2F подзаголовок')),
                ('contactsTitle', models.CharField(default='', max_length=255, verbose_name='Контакты Заголовок')),
            ],
            options={
                'verbose_name': 'Страница Услуги',
                'verbose_name_plural': 'Страница Услуги',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'Страница О нас', 'verbose_name_plural': 'Страница О нас'},
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='AboutPageServicesSubtitle',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='AboutPageServicesTitle',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='AboutPageTitle',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contactsTitle',
            field=models.CharField(default='', max_length=255, verbose_name='Контакты Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='headerTitle',
            field=models.CharField(default='', max_length=255, verbose_name='О нас Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='philosophyMainTitle',
            field=models.CharField(default='', max_length=255, verbose_name='Философия Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='philosophyPhoto',
            field=models.ImageField(default='', max_length=255, upload_to='main/', verbose_name='Философия Фото'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='philosophyPhotoTitle',
            field=models.CharField(default='', max_length=255, verbose_name='Заголовок Фотографии'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='philosophydescription',
            field=models.CharField(default='', max_length=255, verbose_name='Описание фотографии'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='reviewPhoto',
            field=models.ImageField(default='', max_length=255, upload_to='main/', verbose_name='Отзыв Фото'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='reviewSubtitle',
            field=models.CharField(default='', max_length=255, verbose_name='Отзыв подзаголовок'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='reviewTitle',
            field=models.CharField(default='', max_length=255, verbose_name='Отзыв Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='serviceButtonSubtitle',
            field=models.CharField(default='', max_length=255, verbose_name='Услуга нижний подзаголовок'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='serviceSubtitle',
            field=models.CharField(default='', max_length=255, verbose_name='Услуга подзаголовок'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='serviceTitle',
            field=models.CharField(default='', max_length=255, verbose_name='Услуга Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='teamPhoto',
            field=models.ImageField(default='', max_length=255, upload_to='main/', verbose_name='Команда Фото'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='teamSubtitle',
            field=models.CharField(default='', max_length=255, verbose_name='Команда подзаголовок'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='teamTitle',
            field=models.CharField(default='', max_length=255, verbose_name='Команда Заголовок'),
        ),
        migrations.AlterField(
            model_name='services',
            name='after',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='service/after/', verbose_name='Фото После'),
        ),
        migrations.AlterField(
            model_name='services',
            name='before',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='service/before/', verbose_name='Фото До '),
        ),
        migrations.AlterField(
            model_name='underservices',
            name='after',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='underServices/after/', verbose_name='Фото После'),
        ),
        migrations.AlterField(
            model_name='underservices',
            name='before',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='underServices/before/', verbose_name='Фото До'),
        ),
    ]
