# Generated by Django 4.1 on 2022-09-10 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0047_servicespage_alter_aboutpage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhilosBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('philosophyPhotoTitle', models.CharField(default='', max_length=255, verbose_name='Заголовок Фотографии')),
                ('philosophydescription', models.CharField(default='', max_length=255, verbose_name='Описание фотографии')),
                ('philosophyPhoto', models.ImageField(default='', max_length=255, upload_to='main/', verbose_name='Философия Фото')),
            ],
            options={
                'verbose_name': 'Фотография философии',
                'verbose_name_plural': 'Фотографии философии',
            },
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='philosophyPhoto',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='philosophyPhotoTitle',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='philosophydescription',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='philosopyBlock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='astramedClinic.philosblog', verbose_name='Заголовок фотографии'),
        ),
    ]
