# Generated by Django 4.1 on 2022-09-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0048_philosblog_remove_aboutpage_philosophyphoto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='serviceButtonSubtitle',
        ),
    ]
