# Generated by Django 4.1 on 2022-09-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0049_remove_aboutpage_servicebuttonsubtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='philosblog',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
    ]
