# Generated by Django 4.1 on 2022-09-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0050_philosblog_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='reviewSubtitle',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Отзыв подзаголовок'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='serviceSubtitle',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Услуга подзаголовок'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='teamSubtitle',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Команда подзаголовок'),
        ),
    ]
