# Generated by Django 4.1.1 on 2022-09-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0051_alter_aboutpage_reviewsubtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='titleBeforeAfter',
            field=models.CharField(default='До и после', max_length=255, verbose_name='Заголовок фотографий'),
        ),
        migrations.AddField(
            model_name='underservices',
            name='titleBeforeAfter',
            field=models.CharField(default='До и после', max_length=255, verbose_name='Заголовок фотографий'),
        ),
    ]
