# Generated by Django 4.1 on 2022-09-13 07:08

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0052_services_titlebeforeafter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(default='', max_length=255, upload_to='main/', verbose_name='Фото услуги')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Фотография услуги',
                'verbose_name_plural': 'Фотографии услуги',
            },
        ),
        migrations.RemoveField(
            model_name='services',
            name='after',
        ),
        migrations.RemoveField(
            model_name='services',
            name='before',
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='links',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Скрытые ссылки'),
        ),
        migrations.AlterField(
            model_name='info',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='underservices',
            name='title',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='services',
            name='otherPhoto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='astramedClinic.servicephoto', verbose_name='Фотографии'),
        ),
    ]
