# Generated by Django 4.1 on 2022-09-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0053_servicephoto_remove_services_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='sort',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Позиция'),
        ),
    ]
