# Generated by Django 4.1 on 2022-09-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0054_services_sort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='finish_date',
        ),
        migrations.AddField(
            model_name='applications',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время бронирования'),
        ),
        migrations.AddField(
            model_name='applications',
            name='userdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='birth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Год рождения'),
        ),
    ]
