# Generated by Django 4.1 on 2022-09-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0056_servicephoto_otherphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicephoto',
            name='otherPhoto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='astramedClinic.services', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='services',
            name='otherPhoto',
            field=models.ForeignKey(blank=True, default=models.CharField(max_length=255, verbose_name='Название терапии'), null=True, on_delete=django.db.models.deletion.CASCADE, to='astramedClinic.servicephoto', verbose_name='Фотографии'),
        ),
    ]
