# Generated by Django 4.1 on 2022-09-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0058_alter_servicephoto_otherphoto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicephoto',
            name='otherPhoto',
        ),
        migrations.RemoveField(
            model_name='services',
            name='otherPhoto',
        ),
        migrations.AddField(
            model_name='servicephoto',
            name='therapy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='astramedClinic.services', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция'),
        ),
    ]
