# Generated by Django 4.1.1 on 2022-09-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0059_remove_servicephoto_otherphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
