# Generated by Django 3.2.15 on 2022-09-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astramedClinic', '0060_pricelist_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='priceFile',
        ),
    ]
